[client]
showErrorDetails = true

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
headless = true
port = 8501

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
